version: '2.4'

services:

  eventstore:
    image: eventstore/eventstore:21.10.2-bionic
    container_name: "eventstore-commons-test"
    ports:
      - "1113:1113"
      - "2113:2113"
    environment:
      EVENTSTORE_MEM_DB: "true"
      EVENTSTORE_RUN_PROJECTIONS: "all"
      EVENTSTORE_INSECURE: "true"
      EVENTSTORE_ENABLE_EXTERNAL_TCP: "true"
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: "true"
      EVENTSTORE_LOG: "/tmp/log-eventstore"
    networks:
      - eventstore-commons-test

networks:
  eventstore-commons-test:
    name: eventstore-commons-test