version: '2.4'

services:

  eventstore:
    image: kurrentplatform/kurrentdb:26.1.0
    container_name: "eventstore-commons-test"
    ports:
      - "1113:1113"
      - "2113:2113"
    environment:
      KURRENTDB_MEM_DB: "true"
      KURRENTDB_RUN_PROJECTIONS: "all"
      KURRENTDB_INSECURE: "true"
      KURRENTDB_LOG: "/tmp/log-eventstore"
    networks:
      - eventstore-commons-test

networks:
  eventstore-commons-test:
    name: eventstore-commons-test