<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.fuin.esc</groupId>
        <artifactId>esc-parent</artifactId>
        <version>0.10.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>esc-bom</artifactId>
    <packaging>pom</packaging>
    <name>esc-bom</name>
    <description>Bill of Materials (BOM) that provides dependency management for all event store commons modules.</description>

    <dependencyManagement>

        <dependencies>

            <dependency>
                <groupId>org.fuin.esc</groupId>
                <artifactId>esc-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.esc</groupId>
                <artifactId>esc-client</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.esc</groupId>
                <artifactId>esc-spi</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.esc</groupId>
                <artifactId>esc-crypto</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.esc</groupId>
                <artifactId>esc-mem</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.esc</groupId>
                <artifactId>esc-jaxb</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.esc</groupId>
                <artifactId>esc-jpa</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.esc</groupId>
                <artifactId>esc-pg</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.esc</groupId>
                <artifactId>esc-jsonb</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.esc</groupId>
                <artifactId>esc-jackson</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.esc</groupId>
                <artifactId>esc-esgrpc</artifactId>
                <version>${project.version}</version>
            </dependency>

        </dependencies>

    </dependencyManagement>

</project>
